name: Mind Maps Generator CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Deploy to GCE
        if: success()
        run: |
          gcloud compute ssh instance-1 --command="cd /path/on/instance && git pull && chmod +x ./startup-script.sh && ./startup-script.sh"
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
